import test from 'node:test';import assert from 'node:assert/strict';import {leavingRows,todayFoodRows,futurePrepRows,handoffReport,validateBackup} from './model.mjs';
const task=(id,extra={})=>({id,title:id,phase:'At your convenience',notes:'',doOn:'2026-10-05',neededFor:'',completedAt:null,...extra});
const state=tasks=>({version:1,tasks,routines:[],checks:{},skips:[]});
test('leaving shows only unfinished future prep, ignoring old flags',()=>{const s=state([task('prep',{neededFor:'2026-10-09'}),task('flag',{mustFinish:true}),task('other'),task('done',{mustFinish:true,completedAt:'2026-10-05T12:00:00Z'})]);assert.deepEqual(leavingRows(s,'2026-10-05').map(t=>t.id),['prep']);assert.equal(validateBackup(s),true)});
test('handoff includes partial prep, notes, completed prep and unfinished history',()=>{const s=state([task('bread',{target:120,actual:70,neededFor:'2026-10-06',notes:'Bottom shelf'}),task('ready',{neededFor:'2026-10-06',completedAt:'2026-10-05T12:00:00Z'}),task('older')]);const r=handoffReport(s,'2026-10-06');assert.match(r,/70\/120 prepared, 50 remaining/);assert.match(r,/Bottom shelf/);assert.match(r,/Already prepared for this day:\n\n• ready/);assert.match(r,/• older/);assert.equal((r.match(/• bread/g)||[]).length,1)});
test('weekly report covers all seven days and keeps same-day task out of prep duplicate',()=>{const s=state([task('same',{neededFor:'2026-10-05'})]);const r=handoffReport(s,'2026-10-05','2026-10-11');assert.match(r,/Sunday Oct 11/);assert.equal((r.match(/• same/g)||[]).length,1)});

test('excluded dated tasks and routines stay in checklist but leave every report section',()=>{const s=state([task('hidden',{excludeFromReport:true,neededFor:'2026-10-06'}),task('visible')]);s.routines=[{id:'warmer',versions:[{from:'2026-10-01',title:'Warmers',notes:'',phase:'First thing',days:[1,2,3,4,5],retired:false,excludeFromReport:true}]}];assert.equal(validateBackup(s),true);const r=handoffReport(s,'2026-10-05','2026-10-11');assert.doesNotMatch(r,/hidden|Warmers/);assert.match(r,/visible/);assert.match(r,/Monday Oct 5/);assert.equal(leavingRows(s,'2026-10-05').length,1)});

test('dates are compact and same-day needed dates are omitted',()=>{const s=state([task('ready',{neededFor:'2026-10-06',completedAt:'2026-10-05T12:00:00Z'}),task('future',{doOn:'2026-10-06',neededFor:'2026-10-09'})]);const r=handoffReport(s,'2026-10-06');assert.match(r,/^Tuesday Oct 6/);assert.match(r,/Needed Friday Oct 9/);assert.doesNotMatch(r,/2026|\(|\)|needed Tuesday/i)});

test('reminders excluded by default and optional inclusion never claims completion',()=>{const s=state([]);s.routines=[{id:'r',versions:[{from:'2026-10-01',title:'Lights',phase:'First thing',notes:'',days:[1],retired:false}]}];assert.doesNotMatch(handoffReport(s,'2026-10-05'),/Lights/);s.routines[0].versions[0].excludeFromReport=false;const r=handoffReport(s,'2026-10-05');assert.match(r,/Daily reminders:\n\n• Lights/);assert.doesNotMatch(r,/Needs completed today|Completed today/)});

test('today food includes same-day work and unfinished advance prep, future prep rolls into needed day',()=>{const s=state([task('cook',{neededFor:'2026-10-05',mustFinish:true}),task('tray'),task('future',{neededFor:'2026-10-06',target:120,actual:70})]);assert.deepEqual(todayFoodRows(s,'2026-10-05').map(t=>t.id),['cook','tray']);assert.deepEqual(futurePrepRows(s,'2026-10-05').map(t=>t.id),['future']);assert.deepEqual(todayFoodRows(s,'2026-10-06').map(t=>t.id),['future']);assert.equal(todayFoodRows(s,'2026-10-06')[0].actual,70);s.tasks[2].completedAt='2026-10-05T12:00:00Z';s.tasks[2].actual=120;assert.equal(todayFoodRows(s,'2026-10-06').length,0);assert.equal(leavingRows(s,'2026-10-05').length,0)});
