export function quantityStatus(target,actual=0){return {done:actual>=target,remaining:Math.max(0,target-actual),percent:Math.min(100,Math.round(actual/target*100))}}
export function recordAmount(s,item,date,actual){if(!Number.isInteger(actual)||actual<0||actual>1000000000)throw new Error('Enter a whole number from 0 to 1,000,000,000.');const at=new Date().toISOString();if(item.kind==='routine'){s.amounts??={};s.amounts[date+'|'+item.id]=actual;if(actual>=item.target)s.checks[date+'|'+item.id]=at;else delete s.checks[date+'|'+item.id]}else{const task=s.tasks.find(t=>t.id===item.id);task.actual=actual;task.completedAt=actual>=task.target?task.completedAt||at:null}}
export const phases=['First thing','After opening','Before breakfast','After breakfast','Before break','After break','Before 1st lunch','Before 2nd lunch','Before 3rd lunch','After final lunch','At your convenience','Closing','Other'];
export function localDate(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
export function shiftDate(s,n){const d=new Date(s+'T12:00:00');d.setDate(d.getDate()+n);return localDate(d)}
export function routineVersion(r,date){return r.versions.filter(v=>v.from<=date).sort((a,b)=>b.from.localeCompare(a.from))[0]}
export function dailyRows(s,date){const tasks=s.tasks.filter(t=>t.doOn===date).map(t=>({...t,kind:'task',done:t.target?quantityStatus(t.target,t.actual||0).done:!!t.completedAt}));if(!s.skips.includes(date))for(const r of s.routines){const v=routineVersion(r,date);if(v&&!v.retired&&v.days.includes(new Date(date+'T12:00:00').getDay()))tasks.push({...v,id:r.id,kind:'routine',actual:s.amounts?.[date+'|'+r.id]||0,done:v.target?quantityStatus(v.target,s.amounts?.[date+'|'+r.id]||0).done:!!s.checks[date+'|'+r.id]})}return tasks}
export function prepRows(s,date){return s.tasks.filter(t=>t.neededFor===date)}
export function overdueRows(s,date){return s.tasks.filter(t=>t.doOn<date&&!t.completedAt&&t.neededFor!==date)}
export function validateBackup(s){const date=x=>typeof x==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(x)&&!isNaN(new Date(x+'T12:00:00').getTime())&&localDate(new Date(x+'T12:00:00'))===x;const text=x=>typeof x==='string'&&x.length<=250;const count=x=>Number.isInteger(x)&&x>=0&&x<=1000000000;const quantities=t=>(t.target===undefined||t.target===null||count(t.target)&&t.target>0)&&(t.actual===undefined||count(t.actual));const base=t=>t&&quantities(t)&&(t.excludeFromReport===undefined||typeof t.excludeFromReport==='boolean')&&(t.mustFinish===undefined||typeof t.mustFinish==='boolean')&&text(t.title)&&t.title.trim()&&phases.includes(t.phase)&&typeof t.notes==='string'&&t.notes.length<=2000;const stamp=x=>x===null||typeof x==='string'&&!isNaN(Date.parse(x));if(!s||s.version!==1||!Array.isArray(s.tasks)||!Array.isArray(s.routines)||!Array.isArray(s.skips)||!s.checks||typeof s.checks!=='object'||Array.isArray(s.checks))return false;const ids=new Set();for(const t of [...s.tasks,...s.routines]){if(!t||typeof t.id!=='string'||ids.has(t.id))return false;ids.add(t.id)}return s.tasks.every(t=>base(t)&&date(t.doOn)&&(!t.neededFor||date(t.neededFor)&&t.neededFor>=t.doOn)&&stamp(t.completedAt))&&s.routines.every(r=>Array.isArray(r.versions)&&r.versions.length>0&&r.versions.every(v=>base(v)&&date(v.from)&&Array.isArray(v.days)&&v.days.every(d=>Number.isInteger(d)&&d>=0&&d<=6)&&typeof v.retired==='boolean'))&&s.skips.every(date)&&(s.amounts===undefined||s.amounts&&typeof s.amounts==='object'&&!Array.isArray(s.amounts)&&Object.entries(s.amounts).every(([k,v])=>date(k.split('|')[0])&&s.routines.some(r=>r.id===k.split('|')[1])&&count(v)))&&Object.entries(s.checks).every(([k,v])=>date(k.split('|')[0])&&s.routines.some(r=>r.id===k.split('|')[1])&&stamp(v));}

export function leavingRows(s,date){return dailyRows(s,date).filter(t=>t.kind==='task'&&!t.done&&(t.mustFinish||t.neededFor&&t.neededFor>date))}
export function reportDate(date){const d=new Date(date+'T12:00:00');return d.toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'})+' ('+d.toLocaleDateString('en-US',{weekday:'long'})+')'}
export function handoffReport(s,start,end=start){
 const lines=[`Kitchen handoff — ${reportDate(start)}${end!==start?' through '+reportDate(end):''}`, 'Based on recorded checkmarks and progress.'];
 const describe=t=>t.title+(t.target?` — ${t.actual||0}/${t.target} prepared${!t.done&&(t.actual||0)<t.target?`, ${t.target-(t.actual||0)} remaining`:''}`:'')+(t.neededFor?` (needed ${reportDate(t.neededFor)})`:'')+(t.notes?` — ${t.notes}`:'');
 for(let date=start;date<=end;date=shiftDate(date,1)){
  lines.push('',reportDate(date));
  const daily=dailyRows(s,date).filter(t=>!t.excludeFromReport), prep=prepRows(s,date).filter(t=>t.doOn!==date&&!t.excludeFromReport).map(t=>({...t,done:!!t.completedAt})), older=overdueRows(s,date).filter(t=>t.doOn<start&&!t.excludeFromReport).map(t=>({...t,done:false}));
  for(const [label,rows] of [['Already prepared for this day',prep.filter(t=>t.done)],['Prep still needed',prep.filter(t=>!t.done)],['Completed daily tasks',daily.filter(t=>t.done)],['Not marked complete',daily.filter(t=>!t.done)],['Earlier unfinished tasks',older]])if(rows.length){lines.push(label+':');rows.forEach(t=>lines.push('• '+describe(t)+(t.mustFinish&&!t.done?' — Before leaving':'')))}
  if(!daily.length&&!prep.length&&!older.length)lines.push('No tasks recorded.');
 }
 return lines.join('\n');
}
